### ISSUE TITLE
[All Cogs] Portability layer for both dpy 2.0 & lower

### ISSUE THREAD

**Issue by TheDiscordHistorian** [TheDiscordHistorian/historian-cogs#14]
cc: @6days9weeks

**Comment by 6days9weeks** [comment]
Ported:
- [Away](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/away)
- [GameStatus](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/gamestatus)
- [Nhentai](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/nhentai)
- [OnConnect](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/on_connect)
- [ScamChecker](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/scamchecker)
- [TotallyNotSpyware](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/totallynotspyware)
- [WhoPingedMe](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/whopingedme)
Left:
- [Anime](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/anime) needed
- [Reactioner](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/reactioner) maybe
- [Roster](https://github.com/TheDiscordHistorian/historian-cogs/tree/main/roster) maybe
-
